{
 "title": "iKuai Exporter",
 "description": "iKuai OS dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "连接状态",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ikuai_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "系统版本",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ikuai_version_info", "legendFormat": "iKuai {{ver_string}}" }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(ikuai_cpu_usage_ratio)", "legendFormat": "{{core}}" }
   ]
  },
  {
   "title": "线路流量",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ikuai_interface_upload_bytes_total",
     "legendFormat": "上行 {{comment}}"
    },
    {
     "expr": "ikuai_interface_download_bytes_total",
     "legendFormat": "下行 {{comment}}"
    }
   ]
  },
  {
   "title": "设备数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ikuai_devices_online_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "连接数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ikuai_interface_connections)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "运行时间",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ikuai_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "内存使用率",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ikuai_memory_used_kibibytes / ikuai_memory_total_kibibytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "实时上行",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ikuai_interface_upload_speed_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "实时下行",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ikuai_interface_download_speed_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "设备监控 - 实时",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "ikuai_device_upload_speed_bytes",
     "legendFormat": "__auto"
    },
    {
     "expr": "ikuai_device_download_speed_bytes",
     "legendFormat": "__auto"
    },
    { "expr": "ikuai_device_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "设备监控 - 总计",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ikuai_device_upload_bytes_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "ikuai_device_download_bytes_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "历史上行",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "ikuai_device_upload_speed_bytes",
     "legendFormat": "{{ip_addr}}"
    }
   ]
  },
  {
   "title": "历史下行",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "ikuai_device_download_speed_bytes",
     "legendFormat": "{{ip_addr}}"
    }
   ]
  },
  {
   "title": "历史连接数",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "ikuai_device_connections", "legendFormat": "{{ip_addr}}" }
   ]
  }
 ]
}