apiVersion: v1
kind: Secret
metadata:
  name: ikuai-credentials
  namespace: monitoring
type: Opaque
stringData:
  addr: "http://192.168.1.1"
  username: "admin"
  password: "admin"
  # token: ""   # v4 路由器填写
